name: deep3d_pytorch
channels:
  - pytorch3d
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=2.108
  - blas-devel=3.9.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - click=8.1.3
  - cloudpickle=2.2.0
  - colorama=0.4.6
  - cudatoolkit=11.1.1
  - cudnn=8.4.1.50
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2022.2.0
  - dataclasses=0.8
  - decorator=5.1.1
  - easydict=1.9
  - ffmpeg=4.3
  - fonttools=4.38.0
  - freetype=2.12.1
  - fsspec=2022.10.0
  - fvcore=0.1.5.post20220512
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - imagecodecs-lite=2019.12.3
  - imageio=2.22.0
  - importlib-metadata=4.11.4
  - intel-openmp=2019.4
  - iopath=0.1.9
  - ipython=7.33.0
  - jedi=0.18.1
  - jpeg=9b
  - kiwisolver=1.4.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.39
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libmklml=2019.0.5
  - libnsl=2.0.0
  - libpng=1.6.38
  - libprotobuf=3.21.8
  - libsqlite=3.39.4
  - libstdcxx-ng=12.1.0
  - libtiff=4.2.0
  - libuv=1.44.2
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libzlib=1.2.13
  - llvm-openmp=14.0.4
  - locket=1.0.0
  - lz4-c=1.9.3
  - magma=2.5.4
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mkl=2020.4
  - mkl-devel=2020.4
  - mkl-include=2020.4
  - munkres=1.1.4
  - nccl=2.14.3.1
  - ncurses=6.3
  - nettle=3.6
  - networkx=2.6.3
  - ninja=1.11.0
  - numexpr=2.7.3
  - numpy=1.21.6
  - openh264=2.1.1
  - openssl=3.0.7
  - packaging=21.3
  - pandas=1.3.5
  - parso=0.8.3
  - partd=1.3.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.3
  - portalocker=2.6.0
  - prompt-toolkit=3.0.31
  - protobuf=4.21.8
  - ptyprocess=0.7.0
  - pygments=2.13.0
  - pyparsing=3.0.9
  - python=3.7.12
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.8.1
  - pytorch-mutex=1.0
  - pytorch3d=0.7.0
  - pywavelets=1.3.0
  - pyyaml=6.0
  - readline=8.1.2
  - scikit-image=0.19.3
  - scipy=1.7.3
  - setuptools=65.5.0
  - sleef=3.5.1
  - sqlite=3.39.4
  - tabulate=0.9.0
  - tifffile=2020.6.3
  - tk=8.6.12
  - toolz=0.12.0
  - torchaudio=0.8.1
  - torchvision=0.9.1
  - tqdm=4.64.1
  - traitlets=5.5.0
  - unicodedata2=14.0.0
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.6
  - yacs=0.1.8
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.4.9
  - pip:
      - absl-py==0.15.0
      - astor==0.8.1
      - astunparse==1.6.3
      - cachetools==5.2.0
      - charset-normalizer==2.1.1
      - dominate==2.6.0
      - flatbuffers==1.12
      - gast==0.2.2
      - google-auth==2.14.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.32.0
      - h5py==2.10.0
      - idna==3.4
      - keras==2.9.0
      - keras-applications==1.0.8
      - keras-preprocessing==1.1.2
      - kornia==0.5.5
      - markdown==3.3.7
      - matplotlib==2.2.5
      - mtcnn==0.1.1
      - oauthlib==3.2.2
      - opencv-python==4.6.0.66
      - opt-einsum==3.3.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pytz==2022.1
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - six==1.15.0
      - tensorboard==1.15.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==1.15.0
      - tensorflow-estimator==1.15.1
      - termcolor==1.1.0
      - trimesh==3.9.20
      - typing-extensions==3.7.4.3
      - urllib3==1.26.12
      - werkzeug==2.1.2
      - wrapt==1.12.1
      - zipp==3.8.0
